try_list = [1,2,3,"a","b","c",0]
print("Orignal list",try_list)
try_list.append('new')
print("After Append",try_list)
try_list.extend(["newlist1", 'newlist2'])
print("After Extend",try_list)
try_list.insert(4, 'inserted')
print("After Insert",try_list)
try_list.remove('inserted')
print("After Remove",try_list)
try_list.pop(-2)
print("After Pop",try_list)
print("Index function (of a)",try_list.index('a'))
print("Count of a", try_list.count('a'))
#print("Sorted List", try_list.sort())
print("Reverse ", try_list.reverse())
copied = try_list.copy()
print("Copied List", copied)
print("Clear list", try_list.clear())